apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  labels:
    app: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: magikarp511/gateway-service:latest  # 🔄 Usa tu imagen en Docker Hub
          ports:
            - containerPort: 8080  # 📌 Puerto que usa `gateway-service`
          env:
            - name: EUREKA_SERVER
              value: "http://eureka-service-service:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
