version: '3.8'

services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8090
        protocol: tcp
        mode: host
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/Pep1Tingeso"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "1253"


  database:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Pep1Tingeso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1253
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  frontend:
    build:
      context: ./FrontEnd/TingesoPep1 
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
