version: '3.8'

services:

  backend-load-balancer:
    image: nginx:latest
    container_name: backend-lb
    ports:
      - "8090:8090"
    volumes:
      - ./nginx/backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3

  frontend-load-balancer:
    image: nginx:latest
    container_name: frontend-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3

  backend1:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/Pep1Tingeso"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "1253"

  backend2:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/Pep1Tingeso"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "1253"

  backend3:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/Pep1Tingeso"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "1253"
      
  frontend1:
    build:
      context: ./FrontEnd/TingesoPep1
      dockerfile: Dockerfile
    depends_on:
      - backend-load-balancer

  frontend2:
    build:
      context: ./FrontEnd/TingesoPep1
      dockerfile: Dockerfile
    depends_on:
      - backend-load-balancer

  frontend3:
    build:
      context: ./FrontEnd/TingesoPep1
      dockerfile: Dockerfile
    depends_on:
      - backend-load-balancer

volumes:
  postgres_data:
