server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArielPinochet/Tingeso20205-1
          default-label: main
          search-paths: PEP2/config-data
