server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          use-ip-address: true
      routes:
        - id: calendario-service
          uri: lb://calendario-service
          predicates:
            - Path=/calendario/**

        - id: clientefrecuente-service
          uri: lb://CLIENTEFRECUENTE-SERVICE
          predicates:
            - Path=/api/clientes/**

        - id: descuento-service
          uri: lb://descuento-service
          predicates:
            - Path=/api/descuentos/**

        - id: reportes-service
          uri: lb://reportes-service
          predicates:
            - Path=/reportes/**

        - id: reservapago-service
          uri: lb://reservapago-service
          predicates:
            - Path=/app/**

        - id: tarifa-especial-service
          uri: lb://tarifa-especial-service
          predicates:
            - Path=/api/tarifas-especiales/**
            
        - id: tarifas-service
          uri: lb://tarifas-service
          predicates:
            - Path=/api/tarifas/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

