server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: calendario-service
          uri: lb://Tingeso.Calendario
          predicates:
            - Path=/calendario/**
        - id: clientefrecuente-service
          uri: lb://clientefrecuente-service
          predicates:
            - Path=/api/clientes/**
          filters:
            - RewritePath=/api/clientes/(?<segment>.*), /${segment}
        - id: descuento-service
          uri: lb://Tingeso.Descuento
          predicates:
            - Path=/descuento/**
        - id: reportes-service
          uri: lb://Tingeso.Reportes
          predicates:
            - Path=/reportes/**
        - id: reservapago-service
          uri: lb://Tingeso.ReservaPago
          predicates:
            - Path=/reservaPago/**
        - id: tarifaespecial-service
          uri: lb://Tingeso.TarifaEspeciales
          predicates:
            - Path=/tarifaEspecial/**
        - id: tarifas-service
          uri: lb://Tingeso.Tarifas
          predicates:
            - Path=/tarifas/**

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info, routes
  endpoint:
    gateway:
      enabled: true
