server:
  port: 0

spring:
  application:
    name: tarifas-service
    
  datasource:
    url: ''  # 🔹 Esto evita que Spring intente configurar una DB
    driver-class-name: ''  # 🔹 No es necesario definir un driver si no hay DB
  jpa:
    database-platform: ''

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
