server:
  port: 0

spring:
  application:
    name: reservapago-service


  datasource:
    url: jdbc:postgresql://${BD_HOST:localhost}:${BD_PORT:5432}/TingesoReservas
    username: ${BD_USER}
    password: ${BD_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: arielpinochetsoza@gmail.com
    password: qoqcwmlkupfksvhm
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
