server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: tarifa-especial-service
  datasource:
    url: jdbc:postgresql://${BD_HOST:localhost}:${BD_PORT:5432}/TarifaEspecial
    username: ${BD_USER}
    password: ${BD_PASS}
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
