apiVersion: v1
kind: Service
metadata:
  name: config-service-service
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8081  # 📌 Ajusta según el puerto de `config-service`
      targetPort: 8081
  type: ClusterIP
