apiVersion: apps/v1
kind: Deployment
metadata:
  name: descuentos-service-deployment
  labels:
    app: descuentos-service
spec:
  selector:
    matchLabels:
      app: descuentos-service
  replicas: 1
  template:
    metadata:
      labels:
        app: descuentos-service
    spec:
      containers:
        - name: descuentos-service
          image: magikarp511/descuentos-service:latest  # 🔄 Usa tu imagen en Docker Hub
          ports:
            - containerPort: 0  # 📌 Ajusta según el puerto de `descuentos-service`
          env:
            - name: BD_HOST
              value: "postgres-service"
            - name: BD_PORT
              value: "5432"
            - name: BD_USER
              value: "postgres"
            - name: BD_PASS
              value: "1253"
            - name: BD_NAME
              value: "tingesodescuentos"
            - name: EUREKA_SERVER
              value: "http://eureka-service-service:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: descuentos-service-service
  labels:
    app: descuentos-service
spec:
  selector:
    app: descuentos-service
  ports:
    - protocol: TCP
      port: 0
      targetPort: 0
  type: LoadBalancer