apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarifa-especial-service-deployment
  labels:
    app: tarifa-especial-service
spec:
  selector:
    matchLabels:
      app: tarifa-especial-service
  replicas: 1
  template:
    metadata:
      labels:
        app: tarifa-especial-service
    spec:
      containers:
        - name: tarifa-especial-service
          image: magikarp511/tarifa-especial-service:latest  # 🔄 Usa tu imagen en Docker Hub
          ports:
            - containerPort: 0  # 📌 Ajusta según el puerto de `tarifa-especial-service`
          env:
            - name: BD_HOST
              value: "postgres-service"
            - name: BD_PORT
              value: "5432"
            - name: BD_USER
              value: "postgres"
            - name: BD_PASS
              value: "1253"
            - name: BD_NAME
              value: "tingesotarifaespecial"
            - name: EUREKA_SERVER
              value: "http://eureka-service-service:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: tarifa-especial-service-service
  labels:
    app: tarifa-especial-service
spec:
  selector:
    app: tarifa-especial-service
  ports:
    - protocol: TCP
      port: 0
      targetPort: 0
  type: LoadBalancer
